ベースラインをとりあえず動かせるところまで
dondakeshimo/signate-j-quants pull request #1
Opened 2021-04-25 05:55 UTC by dondakeshimo

@Masa-kuchii @IkuyaYamada

https://japanexchangegroup.github.io/J-Quants-Tutorial/ の6章の内容が動くようにしました。

### backtest
backtestの動作確認は行っていません。
とりあえずコピペだけしました。

### src
`module.py` `predictor.py` は https://github.com/JapanExchangeGroup/J-Quants-Tutorial/tree/main/handson/Chapter06/archive/src をまるっとコピペしました。

### hack
簡単なシェルスクリプトです。
こちらのスクリプトで成果物が正しく生成されることは確認しています。
https://signate.jp/competitions/443/submissions

### docker
動作環境としてdocker(1.19以上)を使用します。
READMEに従ってコマンドを打てばmain関数が実行されます。

2021-04-25 06:25 UTC, Masa-kuchii approved these changes, later dismissed

2021-04-25 06:36 UTC, dondakeshimo reviewed
レビュー用補足コメントを追加

2021-04-25 06:36 UTC, dondakeshimo commented on README.md
> +
この辺の手順一回試してみてほしい

2021-04-25 06:36 UTC, dondakeshimo commented on backtest/backtest.py
> +import numpy as np
コピペなのでチェック不要

2021-04-25 06:36 UTC, dondakeshimo commented on docker-compose.yml
> +services:
作ったはいいけどこれは使わなさそうなのでチェック不要

2021-04-25 06:36 UTC, dondakeshimo commented on hack/make_submit.sh
> +#!/bin/bash
一回使ってみてほしい

2021-04-25 06:36 UTC, dondakeshimo commented on ipynb/test_backtest.ipynb
> +{
左上の三点リーダーから `View File` を選ぶと内容が見れる

2021-04-25 06:36 UTC, dondakeshimo commented on requirements.txt
> +fugashi==1.0.5
コピペなのでチェック不要

2021-04-25 06:36 UTC, dondakeshimo commented on src/main.py
> +print("\n".join(ret.split("\n")[:10]))
実行部分
同じようなことをSignateのランタイム環境でやっていると思われる

2021-04-25 06:36 UTC, dondakeshimo commented on src/module.py
> +import math
コピペなのでチェック不要

2021-04-25 06:36 UTC, dondakeshimo commented on src/predictor.py
> +# -*- coding: utf-8 -*-
コピペなのでチェック不要

2021-04-25 12:33 UTC, Masa-kuchii submitted a review, later dismissed

2021-04-25 16:30 UTC, IkuyaYamada requested changes
「BERTに使用する学習済みモデルをダウンロードする」のとこで Docker のビルドが先に必要

2021-04-25 16:30 UTC, IkuyaYamada commented on README.md
> +$ docker run --rm -it -v $(pwd):/opt/ml dondakeshimo/signate-j-quants python hack/download_bert_model.py
細かい点だけど上から順にやっていくとすると、Docker のビルドが先に必要かな
`$ docker build . -t dondakeshimo/signate-j-quants`

2021-04-25 16:30 UTC, IkuyaYamada commented on README.md
> +$ docker run --rm -it -v $(pwd):/opt/ml dondakeshimo/signate-j-quants python hack/download_bert_model.py
もしくは実行方法のところにマージしてしまうのもありかも

2021-04-25 16:50 UTC, dondakeshimo commented on README.md
> +$ docker run --rm -it -v $(pwd):/opt/ml dondakeshimo/signate-j-quants python hack/download_bert_model.py
修正した！

2021-04-26 11:01 UTC, IkuyaYamada approved these changes
完璧でござんす

2021-04-26 12:30 UTC, dondakeshimo commented
@Masa-kuchii @IkuyaYamada 
確認ありがとうございます。
マージします。

2021-04-26 12:30 UTC, merged